on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_API_KEY }}:${{ secrets.API_DEFINITION_ID}}
          oas-file-path: '../../openapi.yml'
          api-version: 1.0
          #rdme: openapi '../../openapi.yml' --key=${{ secrets.README_API_KEY }} --id=${{ secrets.API_DEFINITION_ID}}
